// src/constants/roles.js
export const ROLE_PERMISSIONS = {
  admin: {
    ingredients: ['view', 'create', 'edit', 'delete'],
    articles: ['view', 'create', 'edit', 'delete'],
    inventory: ['view', 'create', 'edit', 'delete'],
    stockcounts: ['view', 'create', 'edit', 'delete', 'count'],
    orders: ['view', 'create', 'edit', 'approve', 'receive', 'finalize', 'delete'],
    mancos: ['view', 'create', 'edit', 'delete'],
    retours: ['view', 'create', 'edit', 'delete'],
    transfers: ['view', 'create', 'edit', 'delete'],
    products: ['view', 'create', 'edit', 'delete'],
    settings: ['view', 'create', 'edit', 'delete'],
    userManagement: ['view', 'edit'],
    lightspeed: ['view', 'create', 'edit', 'delete'],
    recipes: ['view', 'create', 'edit', 'delete'],
    analytics: ['view', 'create', 'edit', 'delete'],
    menuengineering: ['view', 'create', 'edit', 'delete'],
    revenuecenter: ['view', 'create', 'edit', 'delete'],
    soldproducts: ['view', 'create', 'edit', 'delete'],
    salespromo: ['view', 'create', 'edit', 'delete'],
    schedule: ['view', 'create', 'edit', 'delete'],
    maintenancecontracts: ['view', 'create', 'edit', 'delete'],
    rebateagreements: ['view', 'create', 'edit', 'delete'],
  },
  staff: {
    ingredients: ['view', 'create', 'edit', 'delete'],
    inventory: ['view', 'create', 'edit', 'delete'],
    stockcounts: ['view', 'create', 'edit', 'delete', 'count'],
    orders: ['view', 'create', 'edit', 'approve', 'receive', 'finalize', 'delete'],
    mancos: ['view'],
    retours: ['view', 'create', 'edit'],
    transfers: ['view', 'create', 'edit', 'delete'],
    products: ['view', 'create', 'edit', 'delete'],
    settings: ['view', 'create', 'edit', 'delete'],
    analytics: ['view'],
    menuengineering: ['view'],
    revenuecenter: ['view', 'create', 'edit'],
    soldproducts: ['view'],
    salespromo: ['view'],
    schedule: ['view'],
    maintenancecontracts: ['view'],
    rebateagreements: ['view'],
  },
  kitchen: {
    ingredients: ['view', 'create', 'edit', 'delete'],
    inventory: ['view', 'create', 'edit', 'delete'],
    stockcounts: ['view', 'create', 'edit', 'delete', 'count'],
    orders: ['view', 'create', 'edit', 'receive', 'delete'],
    mancos: ['view'],
    retours: ['view', 'create', 'edit'],
    transfers: ['view', 'create', 'edit', 'delete'],
    products: ['view', 'create', 'edit', 'delete'],
    settings: ['view', 'create', 'edit', 'delete'],
    analytics: ['view'],
    menuengineering: ['view'],
    revenuecenter: ['view', 'create', 'edit'],
    soldproducts: ['view'],
    salespromo: ['view'],
    schedule: ['view'],
    maintenancecontracts: ['view'],
    rebateagreements: ['view'],
  },
  night: {
    salespromo: ['view', 'create', 'edit', 'delete'],
  },
  viewer: {
    ingredients: ['view'],
    articles: ['view'],
    inventory: ['view'],
    stockcounts: ['view'],
    orders: ['view'],
    mancos: ['view'],
    retours: ['view'],
    transfers: ['view'],
    products: ['view'],
    settings: [],
    lightspeed: ['view'],
    analytics: ['view'],
    menuengineering: ['view'],
    recipes: ['view'],
    revenuecenter: ['view'],
    soldproducts: ['view'],
    salespromo: ['view'],
    schedule: ['view'],
    maintenancecontracts: ['view'],
    rebateagreements: ['view'],
  },
  producteditor: {
    products: ['view', 'create', 'edit'],
  },
  transfereditor: {
    transfers: ['view', 'create', 'edit'],
  },
  articleeditor: {
    articles: ['view', 'create', 'edit'],
  },
};
